export type IrregularVerb = { v1: string; v2: string; v3: string; tr: string };

// En sık kullanılan düzensiz fiiller (V1 yalın / V2 geçmiş / V3 partisip).
export const IRREGULAR_VERBS: IrregularVerb[] = [
  { v1: "be", v2: "was/were", v3: "been", tr: "olmak" },
  { v1: "become", v2: "became", v3: "become", tr: "olmak/haline gelmek" },
  { v1: "begin", v2: "began", v3: "begun", tr: "başlamak" },
  { v1: "break", v2: "broke", v3: "broken", tr: "kırmak" },
  { v1: "bring", v2: "brought", v3: "brought", tr: "getirmek" },
  { v1: "buy", v2: "bought", v3: "bought", tr: "satın almak" },
  { v1: "come", v2: "came", v3: "come", tr: "gelmek" },
  { v1: "do", v2: "did", v3: "done", tr: "yapmak" },
  { v1: "drink", v2: "drank", v3: "drunk", tr: "içmek" },
  { v1: "drive", v2: "drove", v3: "driven", tr: "araba sürmek" },
  { v1: "eat", v2: "ate", v3: "eaten", tr: "yemek" },
  { v1: "feel", v2: "felt", v3: "felt", tr: "hissetmek" },
  { v1: "find", v2: "found", v3: "found", tr: "bulmak" },
  { v1: "get", v2: "got", v3: "got/gotten", tr: "almak/olmak" },
  { v1: "give", v2: "gave", v3: "given", tr: "vermek" },
  { v1: "go", v2: "went", v3: "gone", tr: "gitmek" },
  { v1: "have", v2: "had", v3: "had", tr: "sahip olmak" },
  { v1: "hear", v2: "heard", v3: "heard", tr: "duymak" },
  { v1: "know", v2: "knew", v3: "known", tr: "bilmek" },
  { v1: "learn", v2: "learnt/learned", v3: "learnt/learned", tr: "öğrenmek" },
  { v1: "leave", v2: "left", v3: "left", tr: "ayrılmak/bırakmak" },
  { v1: "make", v2: "made", v3: "made", tr: "yapmak" },
  { v1: "meet", v2: "met", v3: "met", tr: "buluşmak/tanışmak" },
  { v1: "pay", v2: "paid", v3: "paid", tr: "ödemek" },
  { v1: "put", v2: "put", v3: "put", tr: "koymak" },
  { v1: "read", v2: "read", v3: "read", tr: "okumak" },
  { v1: "run", v2: "ran", v3: "run", tr: "koşmak" },
  { v1: "say", v2: "said", v3: "said", tr: "söylemek" },
  { v1: "see", v2: "saw", v3: "seen", tr: "görmek" },
  { v1: "sell", v2: "sold", v3: "sold", tr: "satmak" },
  { v1: "send", v2: "sent", v3: "sent", tr: "göndermek" },
  { v1: "sit", v2: "sat", v3: "sat", tr: "oturmak" },
  { v1: "sleep", v2: "slept", v3: "slept", tr: "uyumak" },
  { v1: "speak", v2: "spoke", v3: "spoken", tr: "konuşmak" },
  { v1: "spend", v2: "spent", v3: "spent", tr: "harcamak" },
  { v1: "take", v2: "took", v3: "taken", tr: "almak" },
  { v1: "teach", v2: "taught", v3: "taught", tr: "öğretmek" },
  { v1: "tell", v2: "told", v3: "told", tr: "söylemek/anlatmak" },
  { v1: "think", v2: "thought", v3: "thought", tr: "düşünmek" },
  { v1: "understand", v2: "understood", v3: "understood", tr: "anlamak" },
  { v1: "wear", v2: "wore", v3: "worn", tr: "giymek" },
  { v1: "win", v2: "won", v3: "won", tr: "kazanmak" },
  { v1: "write", v2: "wrote", v3: "written", tr: "yazmak" },
];
